version: '3'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=2004
      - DATABASE_NAME=cloudy_members
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=2004
      - MYSQL_DATABASE=cloudy_members
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
